export enum USER_ROLE {
    SUPER_ADMIN = "SUPER_ADMIN",
    ADMIN = "ADMIN",
    USER = "USER",
    DONNER = "DONNER"
}


export enum DIVISION_NAME {
    DHAKA = "DHAKA",
    CHATTOGRAM = "CHATTOGRAM",
    RAJSHAHI = "RAJSHAHI",
    KHULNA = "KHULNA",
    BARISHALL = "BARISHALL",
    SYLHET = "SYLHET",
    RANGPUR = "RANGPUR",
    MYMENSINGH = "MYMENSINGH",
}